import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { analysisId } = await req.json();
    if (!analysisId) {
      return new Response(JSON.stringify({ error: "Missing analysisId" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: analysis, error: fetchError } = await supabase
      .from("risk_analyses")
      .select("*")
      .eq("id", analysisId)
      .eq("user_id", user.id)
      .single();

    if (fetchError || !analysis) {
      return new Response(JSON.stringify({ error: "Analysis not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const inputs = analysis.inputs as Record<string, unknown>;
    const riskScore = analysis.risk_score as Record<string, unknown>;
    const suggestions = analysis.suggestions as Array<Record<string, unknown>>;

    // Generate a text-based report (PDF-like content as downloadable text)
    const report = `
══════════════════════════════════════════════════════════
           RISKTWIN - FINANCIAL RISK ANALYSIS REPORT
══════════════════════════════════════════════════════════

Generated: ${new Date(analysis.created_at).toLocaleString()}
Report ID: ${analysis.id}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  COMPANY PROFILE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Company Name:       ${analysis.company_name}
  Industry:           ${analysis.industry}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  FINANCIAL METRICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Monthly Revenue:        $${Number(inputs.monthlyRevenue).toLocaleString()}
  Monthly Burn Rate:      $${Number(inputs.monthlyBurnRate).toLocaleString()}
  Total Funding:          $${Number(inputs.totalFunding).toLocaleString()}
  Cash on Hand:           $${Number(inputs.cashOnHand).toLocaleString()}
  Team Size:              ${inputs.headcount}
  Customer Count:         ${inputs.customerCount}
  Monthly Churn Rate:     ${inputs.churnRate}%
  Revenue Growth Rate:    ${inputs.revenueGrowthRate}%
  Debt-to-Equity Ratio:  ${inputs.debtToEquityRatio}
  Operating Margin:       ${inputs.operatingMargin}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  RISK ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ★ Overall Risk Score:   ${riskScore.overall}/100 (${riskScore.label})

  Risk Breakdown:
  ├── Financial Risk:     ${riskScore.financial}/100
  ├── Operational Risk:   ${riskScore.operational}/100
  ├── Market Risk:        ${riskScore.market}/100
  └── Growth Risk:        ${riskScore.growth}/100

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  AI-DRIVEN SUGGESTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${suggestions.map((s: Record<string, unknown>, i: number) => `  ${i + 1}. [${String(s.impact).toUpperCase()}] ${s.title}
     ${s.description}
     Category: ${s.category}
`).join("\n")}

══════════════════════════════════════════════════════════
  This report was generated by RiskTwin Financial Risk
  Intelligence Platform. For questions, contact support.
══════════════════════════════════════════════════════════
`;

    return new Response(report, {
      headers: {
        ...corsHeaders,
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="RiskTwin_Report_${analysis.company_name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt"`,
      },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
